using System;
using System.Collections.Generic;

namespace Hofinsoft.Mdg.Models
{
    public class ProductionCatalog
    {
        public int Id { get; set; }
        
        // Finalized Golden Record Unique ID
        public string UniqueId { get; set; } = string.Empty;
        
        public string Noun { get; set; } = string.Empty;
        
        public string Modifier { get; set; } = string.Empty;
        
        // Finalized Key-Value pairs of material attribute values
        public Dictionary<string, string> AttributeValues { get; set; } = new();
        
        // Standardized description nomenclature generated by the governance engine
        public string Description { get; set; } = string.Empty;
        
        public DateTime ApprovedAt { get; set; } = DateTime.UtcNow;
    }
}
