using System.Collections.Generic;

namespace Hofinsoft.Mdg.Models
{
    public class StagingItemRequest
    {
        public int Id { get; set; }
        
        // Calculated Unique ID based on noun, modifier, and attributes
        public string UniqueId { get; set; } = string.Empty;
        
        public string Noun { get; set; } = string.Empty;
        
        public string Modifier { get; set; } = string.Empty;
        
        // Key-Value pairs of material attribute values (e.g., Inside_Diameter -> 15mm)
        public Dictionary<string, string> AttributeValues { get; set; } = new();
        
        // Standardized description nomenclature generated by the governance engine
        public string Description { get; set; } = string.Empty;
        
        // Staged status: Draft, Pending, or Approved
        public ApprovalStatus Status { get; set; } = ApprovalStatus.Draft;
    }
}
